overtime/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from . import views

app_name = 'overtime'
urlpatterns = [
	url(r'^add/$', views.add_overtime, name='add'),
	url(r'^request/$', views.overtimerequest, name='requestform'),
	#url(r'^list/(?P<page>[0-9]+)/$', login_required(views.OvertimeListView.as_view()), name='list'),
	url(r'^list/(?P<page>[0-9]+)/$', views.overtime_list, name='list'),
	url(r'^list/(?P<page>[0-9]+)/add-actual-hours/$', views.add_actual_hours, name='actualhours'), 
]

users/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'users'
urlpatterns = [
	#url(r'^settings/$', auth_views.PasswordChangeView.as_view(template_name='users/pwd_change.html', success_url='/'), name='settings'),
	url(r'^set-password/$', views.change_password, name='setpassword'),
	#url(r'^set-homepage/$', views.set_home_projects, name='setlinks'),
]

overtime/models.py
from django.db import models
from django.conf import settings
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

from employees.models import Employee
from projects.models import Project


class Overtime(models.Model):
	"""model representing an occurance of overtime work"""
	class Meta:
		permissions = (('view_overtime', _('Can view overtime')),)
		ordering = ['-date']
		verbose_name=_('overtime')
		verbose_name_plural=_('overtime')


	# validate for hours fields (0 hrs < hours < 24 hrs & res = .5 hrs)
	def validate_hours(hours):
		if hours > 24:
			raise ValidationError(_('Overtime hours cannot exceed 24 hours for a given day'))
		elif hours < 0:
			raise ValidationError(_('Overtime hours must be greater than 0'))
		elif float(hours) % .5 != 0: # is this true?
			raise ValidationError(_('Overtime hours must be recorded to the half hour'))

	date = models.DateField(verbose_name=_('date'))
	time = models.TimeField(verbose_name=_('time'))
	request_hours = models.DecimalField(max_digits=3, decimal_places=1, validators=[validate_hours], verbose_name=_('request hours'))
	actual_hours = models.DecimalField(max_digits=3, decimal_places=1, blank=True, null=True, validators=[validate_hours], verbose_name=_('hours worked'))
	emp = models.ForeignKey(Employee, on_delete=models.PROTECT, related_name='overtime', verbose_name=_('employee'))
	project = models.ForeignKey(Project, on_delete=models.PROTECT, verbose_name=_('project')) #choice limiting done at the form level
	reason = models.CharField(max_length=120, verbose_name=_('reason'))

	def __str__(self):
		return self.emp.english_name + ' - ' + str(self.date)

overtime/forms.py
from datetime import timedelta, date as pydate

from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

from .models import Overtime
from employees.models import Employee
from projects.models import Project, Defaults

class AddOvertime(forms.ModelForm):
	"""form for employees to use to add overtime"""
	'''
	def __init__(self, *args, **kwargs):
		self.user = kwargs.pop('user')
		self.project = forms.ModelChoiceField(queryset=Project.objects.filter(engineer=self.user.employee), label=_('project'))
		super(AddOvertime, self).__init__(*args, **kwargs)
	'''
	def validate_date(date):
		if date < pydate.today():
			raise ValidationError(_('Cannot submit for overtime in the past'))
		elif date - pydate.today() > timedelta(days=2):
			raise ValidationError(_('Cannot submit for overtime more than 2 days in advance'))

	date = forms.DateField(validators=[validate_date], label=_('Date'))
	request_hours = forms.DecimalField(validators=[Overtime.validate_hours], max_digits=3, decimal_places=1, label=_('Request hours'), widget=forms.TextInput(attrs={'type':'number', 'step':'0.5'}))
	reason = forms.ChoiceField(choices=[('','---------')]+[(str(x[1]),x[1]) for x in Defaults.WORK_REASON], label=_('Reason'))
	
	class Meta:
		model = Overtime
		fields = ['date', 'time', 'request_hours', 'project', 'reason']


class DatePicker(forms.Form):
	"""form to pick the date for overtime retrieval"""
	years = [x for x in range(2017, pydate.today().year+1)] # 2017 to current year
	date = forms.DateField(widget=forms.SelectDateWidget(years=years, empty_label=None), initial=pydate.today(), label=_('Date')) 
	# calendar widget? default to today?


class OvertimeFilter(forms.Form):
	"""docstring for OvertimeFilter"""
	years = [x for x in range(2017, pydate.today().year+1)] # 2017 to current year
	date = forms.DateField(required=False, widget=forms.SelectDateWidget(years=years, empty_label=''), label=_('Date'))
	emp = forms.ModelChoiceField(required=False, queryset=Employee.objects.all(), empty_label='', label=_('Employee'))
	project = forms.ModelChoiceField(required=False, queryset=Project.objects.filter(status='INP'), empty_label='', label=_('Project'))

class ActualHoursForm(forms.Form):
	"""form to input actual overtime hours worked"""
	actual_hours = forms.DecimalField(validators=[Overtime.validate_hours], max_digits=3, decimal_places=1, label=_('Request hours'), widget=forms.TextInput(attrs={'type':'number','step':'0.5'}))
	overtime_id = forms.IntegerField(min_value=0, max_value=Overtime.objects.count())
	

overtime/views.py
from datetime import date as Date

from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, CreateView, UpdateView
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import permission_required, login_required
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.http import HttpResponse, HttpResponseRedirect
from django.db.models.query import QuerySet
from django.urls import reverse_lazy
from django.core.paginator import Paginator
from django.utils.translation import ugettext_lazy as _

from EngSite.utils.reportgen import generate_overtime_report
from projects.models import Project
from .models import Overtime
from .forms import AddOvertime, DatePicker, OvertimeFilter, ActualHoursForm

@permission_required('overtime.add_overtime', raise_exception=True)
def add_overtime(request):
	context = {}
	if request.method == 'POST':
		ot = Overtime.objects.filter(date=request.POST.get('date')).filter(emp=request.user.employee)
		if ot.count() == 0: # a lot of extra work just for a small notification (necessary?)
			form = AddOvertime(request.POST)  #, user=request.user
			form.instance.emp = request.user.employee # need way to test and catch users w/o attached employees 
			context['notice'] = _('Overtime recorded successfully')
		else:
			form = AddOvertime(request.POST, instance=ot[0])  #, user=request.user
			context['notice'] = _('Previously submitted overtime has been overwritten')

		if form.is_valid():
			form.save()
		else:
			context['notice'] = _('Not saved. Invalid data.')
	else:
		form = AddOvertime(initial={'date': Date.today()}) #, user=request.user
	context['form'] = form
	return render(request, 'overtime/add.html', context)


@permission_required('overtime.view_overtime', raise_exception=True)
def overtimerequest(request):
	context = {}
	if request.method == 'POST':
		# makes the pdf with the sent info
		form = DatePicker(request.POST)
		if form.is_valid():
			date = form.cleaned_data['date']
			ot = Overtime.objects.filter(date=date)
			if ot.exists():
				response = HttpResponse(generate_overtime_report(overtime=ot), content_type='application/vnd.ms-excel')
				response['Content-Disposition'] = 'attachment; filename="' + str(date) + '_Overtime.xlsx"'
				return response
			else:
				context['notice'] = _('No overtime recorded on selected date')
		else:
			context['notice'] = _('Invalid date provided')
	# user requests the date selection page
	form = DatePicker()
	context['dateform'] = form
	return render(request, 'overtime/request.html', context)


class OvertimeListView(PermissionRequiredMixin, ListView):
	"""handles the overtime list view"""
	raise_exception = True
	permission_required = 'overtime.view_overtime'
	template_name = 'overtime/list.html'
	model = Overtime
	paginate_by = 50

	def get_queryset(self, **kwargs):
		# isn't executed every time 
		qs = super(OvertimeListView, self).get_queryset(**kwargs)
		if self.request.method == 'GET': 
			if self.request.GET.get('emp') != '' and self.request.GET.get('emp') != None:
				qs = qs.filter(emp=self.request.GET.get('emp'))
			if self.request.GET.get('date_day') != None and self.request.GET.get('date_month') != None and self.request.GET.get('date_year') != None:
				try:
					y = int(self.request.GET.get('date_year'))
					m = int(self.request.GET.get('date_month'))
					d = int(self.request.GET.get('date_day'))
					qs = qs.filter(date=Date(y,m,d))
				except ValueError:
					pass
			if self.request.GET.get('project') != '':
				qs = qs.filter(project=self.request.GET.get('project'))
		return qs

	def get_context_data(self, **kwargs):
		# rarely is executed
		context = super(OvertimeListView, self).get_context_data(**kwargs)
		context['form'] = OvertimeFilter()
		return context

@login_required
@permission_required('overtime.view_overtime', raise_exception=True)
def overtime_list(request, page):
	ot = Overtime.objects.all()
	form = OvertimeFilter()
	if request.GET:
		y = int(request.GET.get('date_year'))
		m = int(request.GET.get('date_month'))
		d = int(request.GET.get('date_day'))
		filters = {
			'emp': request.GET.get('emp'),
			'project': request.GET.get('project'),
		}
		if filters['emp'] != '':
			ot = ot.filter(emp=filters['emp'])
		#if request.GET.get('date_day') != None and request.GET.get('date_month') != None and request.GET.get('date_year') != None:
		if d > 0 and m > 0 and y > 2000:
			ot = ot.filter(date=Date(y,m,d))
			filters['date_year'] = y
			filters['date_month'] = m
			filters['date_day'] = d
		if filters['project'] != '':
			ot = ot.filter(project=filters['project'])
		form = OvertimeFilter(filters)
	paginator = Paginator(ot, 50)
	context = {'form': form, 'page_obj': paginator.page(page), 'overtime': Overtime, 'AH_form':ActualHoursForm()}
	return render(request, 'overtime/list.html', context)

@require_POST
@permission_required('overtime.change_overtime', raise_exception=True)
def add_actual_hours(request, page):
	AH_form = ActualHoursForm(request.POST)
	if AH_form.is_valid():
		overtime = get_object_or_404(Overtime, pk=AH_form.cleaned_data['overtime_id'])
		assert overtime.id == AH_form.cleaned_data['overtime_id']
		overtime.actual_hours = AH_form.cleaned_data['actual_hours']
		overtime.save()
	return HttpResponseRedirect('/overtime/list/' + page)

overtime/templates/overtime/add.html
{% extends "page.html" %}

{% load i18n %}

{% block title %} Request Overtime {% endblock title %}

{% block pagecontent %}
<div class="container">
	<div class="border-around" style="display: inline-block;">
		<h3>{% trans "Request Overtime" %}</h3>
		<p> {{notice}} </p>
		<form action='{% url "overtime:add" %}' method='post'>
			{% csrf_token %}
			<table>
				{{ form.as_table }}
			</table>
			<input type="submit" value="{% trans 'Submit' %}">
		</form>
	</div>
</div>
{% endblock pagecontent %}

overtime/templates/overtime/list.html
{% extends "page.html" %}

{% load custom i18n %}

{% block title %} Overtime List {% endblock %}

{% block pagecontent %}
<div class="pad-list">
	<h3>{% trans "Overtime List" %}</h3>
	<form action="{% url 'overtime:list' 1 %}" method="get">
		{{form}}
		<input type="submit" value="{% trans 'Filter' %}">
	</form>
	<div class="table-responsive">
		<table class="table table-striped">
			<tr>
				<th>{{overtime|verbose_name:'emp'|title}}</th>
				<th>{{overtime|verbose_name:'project'|title}}</th>
				<th>{{overtime|verbose_name:'date'|title}}</th>
				<th>{{overtime|verbose_name:'time'|title}}</th>
				<th>{{overtime|verbose_name:'request_hours'|title}}</th>
				<th>{{overtime|verbose_name:'actual_hours'|title}}</th>
				<th>{{overtime|verbose_name:'reason'|title}}</th>
			</tr>
			{% for ot in page_obj %}
			<tr class="notice-me">
				{% if request.LANGUAGE_CODE == 'zh-hans' %}
				<td>{{ot.emp.name}}</td>
				{% else %}
				<td>{{ot.emp.english_name}}</td>
				{% endif %}
				<td>{{ot.project}}</td>
				<td>{{ot.date}}</td>
				<td>{{ot.time}}</td>
				<td>{{ot.request_hours|floatformat}}</td>
				{% if ot.actual_hours %}
				<td>{{ot.actual_hours|floatformat}}</td>
				{% else %}
				<td><form method="POST" action="{% url 'overtime:actualhours' page_obj.number %}">
					{% csrf_token %}
					{{AH_form.actual_hours}}
					<input style="display: none;" type="number" name="overtime_id" id="id_overtime_id" value="{{ot.id}}" required>
					<input type="submit" value="{% trans 'Update' %}">
				</form></td>
				{% endif %}
				<td>{{ot.reason}}</td>
			</tr>
			{% empty %}
			<tr><td>{% trans "No overtime records found" %}</td><td></td><td></td><td></td><td></td><td></td></tr>
			{% endfor %}
		</table>
	</div>
	<div class="row">
		<div class="col-xs-4 col-md-5"><hr style="border:none;color:#333;background-color:#333" /></div>
		<div class="col-xs-4 col-md-2" style="text-align: center;">
			<span style="font-size: 1.5em;">
				{% if page_obj.has_previous %}
					<a href="{% url 'overtime:list' page_obj.previous_page_number %}"><i class="glyphicon glyphicon-chevron-left" style="color: #333"></i></a>
				{% else %}
					<!-- placeholder to ensure it remains centered -->
					<i class="glyphicon glyphicon-chevron-left" style="visibility: hidden;"></i>
				{% endif%}
				<span>{{page_obj.number}}</span>
				{% if page_obj.has_next %}
					<a href="{% url 'overtime:list' page_obj.next_page_number %}"><i class="glyphicon glyphicon-chevron-right" style="color: #333"></i></a>
				{% else %}
					<!-- placeholder to ensure it remains centered -->
					<i class="glyphicon glyphicon-chevron-right" style="visibility: hidden"></i>
				{% endif%}
			</span>
		</div>
		<div class="col-xs-4 col-md-5"><hr style="border:none;color:#333;background-color:#333" /></div>
	</div>
</div>
{% endblock pagecontent %}

overtime/templates/overtime/request.html
{% extends "page.html" %}

{% load i18n %}

{% block pagecontent %}

<div class="container">
	<div class="border-around" style="display: inline-block;">
		<h3>{% trans "Download Overtime Records" %}</h3>
		{% if notice %}
		<p>{{notice}}</p>
		{% endif %}

		<form action="{% url 'overtime:requestform' %}" method='post'>
			{% csrf_token %}
			{{dateform}}
			<input type="submit" value="{% trans 'Download' %}">
		</form>
	</div>
</div>

{% endblock pagecontent %}