overtime/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from . import views

app_name = 'overtime'
urlpatterns = [
	url(r'^add/$', views.add_overtime, name='add'),
	url(r'^request/$', views.overtimerequest, name='requestform'),
	#url(r'^list/(?P<page>[0-9]+)/$', login_required(views.OvertimeListView.as_view()), name='list'),
	url(r'^list/(?P<page>[0-9]+)/$', views.overtime_list, name='list'),
	url(r'^list/(?P<page>[0-9]+)/add-actual-hours/$', views.add_actual_hours, name='actualhours'), 
]

projects/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
#from django.views.generic import DetailView
from . import views

app_name = 'projects'
urlpatterns = [
	url(r'^$', login_required(views.ProjectListView.as_view()), name='projectlist'),
	url(r'^(?P<pid>[0-9]+)/$', views.project_page, name='dashboard'),
	url(r'^(?P<pid>[0-9]+)/status_update/$', views.change_project_status, name='statusupdate'),
	url(r'^(?P<pid>[0-9]+)/add_part_number/(?P<org>eastek|customer)/$', views.add_part_number, name='partnumupdate'),
	url(r'^(?P<pid>[0-9]+)/join_project/$', views.add_self_to_project, name='joinproject'),
	url(r'^add/$', views.add_project, name='addproject'),
	#url(r'^(?P<pid>[0-9]+)/milestones/$', views.project_milestones, name='milestones'),
	#url(r'^(?P<pid>[0-9]+)/milestones/completion_status$', views.change_milestone_completion, name='milestonecompletion'),
	url(r'^(?P<pid>[0-9]+)/updates/$', views.project_updates, name='updates'),
	url(r'^(?P<pid>[0-9]+)/updates/add/$', views.add_update, name='addupdate'),
	url(r'^(?P<pid>[0-9]+)/gate/(?P<gate>[12345])/$', views.complete_checklist, name='checklist'),
	url(r'^(?P<pid>[0-9]+)/download/(?P<gate>[12345])/$', views.download_checklist, name='downloadchecklist'),
	url(r'^customers/$', views.CustomerListView.as_view(), name='customers'),
	url(r'^customers/add_new_customer/$', views.add_customer, name='addcustomer'),

]

users/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'users'
urlpatterns = [
	#url(r'^settings/$', auth_views.PasswordChangeView.as_view(template_name='users/pwd_change.html', success_url='/'), name='settings'),
	url(r'^set-password/$', views.change_password, name='setpassword'),
	#url(r'^set-homepage/$', views.set_home_projects, name='setlinks'),
]

projects/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth import get_user_model

from users.models import User
from employees.models import Employee
from . import models

class ProjectFilter(forms.Form):
	"""docstring for ProjectFilter"""
	customer = forms.ModelChoiceField(required=False, queryset=models.Customer.objects.all(), empty_label='', label=_('Customer'))
	work_type = forms.ChoiceField(required=False, choices=(('',''),)+models.Project.WORK_TYPES, label=_('Project type'))
	status = forms.ChoiceField(required=False, choices=(('',''),)+models.Project.STATUS, label=_('Status'))
	engineer = forms.ModelChoiceField(required=False, queryset=Employee.objects.filter(is_active=True), empty_label='', label=_('Engineer'))


class ProjectStatusForm(forms.Form):
	"""docstring for ProjectStatusForm"""
	status = forms.ChoiceField(choices=models.Project.STATUS, label=_('Status'))


class CheckForm(forms.Form):
	"""docstring for CheckForm"""
	chk = forms.BooleanField(required=False)

CheckFormset = forms.formset_factory(CheckForm)
		

class ProjectForm(forms.ModelForm):
	"""docstring for ProjectForm"""
	engineer = forms.ModelChoiceField(required=False, queryset=Employee.objects.filter(is_active=True).exclude(team='SUPP'), empty_label='---------', label=_('Engineer'))
	class Meta:
		model = models.Project
		fields = ['name', 'customer', 'eastek_pn', 'cust_pn', 'engineer', 'work_type', 'status'] #lead_eng

class PartNumForm(forms.Form):
	partnum = forms.CharField(max_length=50, min_length=5, strip=True, label=_('part number'))


class MilestoneForm(forms.ModelForm):
	"""docstring for MilestoneForm"""
	deadline = forms.DateField(widget=forms.DateInput(attrs={'class':'deadline-input'}), label=_('deadline'))
	class Meta:
		model = models.Milestone
		fields = ['description', 'deadline']

class UpdateForm(forms.ModelForm):
	"""docstring for UpdateForm"""
	project = forms.CharField(widget=forms.HiddenInput())
	mod_user = forms.ModelChoiceField(queryset=get_user_model().objects.all(), to_field_name='id', widget=forms.HiddenInput())
	estimated_hours = forms.IntegerField(max_value=500, min_value=0, label=_('Estimated hours'))

	class Meta:
		model = models.Update
		fields =['project', 'stage', 'action_required', 'estimated_hours', 'mod_user']
		widgets = {'action_required': forms.Textarea(attrs={'rows': 4})}

	def clean_project(self):
		try:
			val = self.cleaned_data['project']
		except AttributeError:
			raise forms.ValidationError()
		try:
			instance = models.Project.objects.get(id=val)
		except Project.DoesNotExist:
			raise forms.ValidationError(_('Associated project not found'))
		return instance

	def clean_mod_user(self):
		try:
			val = self.cleaned_data['mod_user']
		except AttributeError:
			raise forms.ValidationError()
		User = get_user_model()
		try:
			instance = User.objects.get(username=val)
		except User.DoesNotExist:
			raise forms.ValidationError(_('User instance not found'))
		return instance


class CustomerForm(forms.ModelForm):
	"""docstring for CustomerForm"""
	class Meta:
		model = models.Customer
		fields = ['name'] # may need to expand later


class ChecklistForm(forms.ModelForm):
	"""docstring for ChecklistForm"""
	def validate_completed(value):
		if value == 'False':
			raise forms.ValidationError(_('Item must be completed or not applicable'))

	completed = forms.ChoiceField(required=False, choices=models.ChecklistItem.COMP_CHOICE, validators=[validate_completed], label=_('Completed'))

	class Meta:
		model = models.ChecklistItem
		fields = ['name', 'responsible', 'completed', 'remarks']


ChecklistFormset = forms.formset_factory(ChecklistForm)

projects/views.py
from datetime import date

from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic import ListView
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import permission_required, login_required
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.forms import formset_factory
from django.utils import translation
from django.db.models import Q

from EngSite.utils.utils import choice_lookup
from EngSite.utils.reportgen import generate_gate_checklist
from employees.models import Employee
from . import models, forms


@login_required
@permission_required('projects.change_project', raise_exception=True)
def project_page(request, pid):
	project = get_object_or_404(models.Project, pk=pid)
	milestones = models.Milestone.objects.filter(project=project.id)
	updates = models.Update.objects.filter(project=project.id)
	form = forms.ProjectStatusForm(initial={'status': project.status})
	if updates.exists():
		status = updates[0]
	else:
		status = None
	context = {'project': project, 
				'projstatus': form, 
				'milestones': milestones, 
				'status': status,
				'work_opts': models.Project.WORK_TYPES,
				'status_opts': models.Project.STATUS,
				'stage_opts': models.Update.STAGES,
				'epn_form': forms.PartNumForm(),
				'cpn_form': forms.PartNumForm(),}
	return render(request, 'projects/project.html', context)


@require_POST
@permission_required('projects.change_project', raise_exception=True)
def change_project_status(request, pid):
	try:
		project = models.Project.objects.get(pk=pid)
	except models.Project.DoesNotExist:
		return HttpResponseRedirect('/projects/' + pid)
	form = forms.ProjectStatusForm(request.POST)
	if form.is_valid():
		project.status = form.cleaned_data['status']
		project.save()
	return HttpResponseRedirect('/projects/' + pid)


@require_POST
@permission_required('projects.change_project', raise_exception=True)
def add_part_number(request, pid, org):
	proj = get_object_or_404(models.Project, pk=pid)
	form = forms.PartNumForm(request.POST)
	if form.is_valid():
		if org == 'eastek':
			proj.eastek_pn = form.cleaned_data['partnum']
		elif org == 'customer':
			proj.cust_pn = form.cleaned_data['partnum']
		proj.save()
	return HttpResponseRedirect('/projects/' + pid)


@require_POST
@permission_required('projects.change_project', raise_exception=True)
def add_self_to_project(request, pid):
	try:
		project = models.Project.objects.get(pk=pid)
	except models.Project.DoesNotExist:
		return HttpResponseRedirect('/projects/' + pid)
	try:
		eng = request.user.employee
	except RelatedObjectDoesNotExist:
		return HttpResponseRedirect('/projects/' + pid)
	project.engineer.add(eng)
	return HttpResponseRedirect('/projects/' + pid)


@require_POST
@permission_required('projects.change_project', raise_exception=True)
def change_milestone_completion(request, pid):
	try:
		project = models.Project.objects.get(pk=pid)
	except models.Project.DoesNotExist:
		return HttpResponseRedirect('/projects/' + pid)
	formset = forms.CheckFormset(request.POST)
	if formset.is_valid():
		for i in range(project.milestone_set.all().count()): 
			ms = project.milestone_set.all()[i]
			try:
				ms.is_complete = formset[i].cleaned_data['chk']
			except KeyError:
				ms.is_complete = False
			ms.save()
	return HttpResponseRedirect('/projects/' + pid)


@login_required
@permission_required('projects.add_project', raise_exception=True)
def add_project(request):
	formset = formset_factory(forms.MilestoneForm)
	default = {'form-TOTAL_FORMS':'5',
				'form-INITIAL_FORMS':'0',
				'form-MIN_NUM_FORMS':'',
				'form-MAX_NUM_FORMS':'',
				'form-0-description': models.Defaults.GATE_LIST[0][0],
				'form-1-description': models.Defaults.GATE_LIST[1][0],
				'form-2-description': models.Defaults.GATE_LIST[2][0],
				'form-3-description': models.Defaults.GATE_LIST[3][0],
				'form-4-description': models.Defaults.GATE_LIST[4][0],}
	if request.method == 'POST':
		proj_form = forms.ProjectForm(request.POST)
		mstn_form = formset(request.POST)
		if proj_form.is_valid() and mstn_form.is_valid():
			proj = proj_form.save()
			for frm in mstn_form:
				ms = frm.save(commit=False)
				ms.project = proj
				ms.save()
			return HttpResponseRedirect('/projects/' + str(proj.id))
	else:
		proj_form = forms.ProjectForm(initial={'status':'INP'})
		mstn_form = formset(default)
	context = {'proj_form': proj_form, 'formset': mstn_form}
	return render(request, 'projects/add_project.html', context)


@login_required
@permission_required('projects.add_update', raise_exception=True)
def add_update(request, pid):
	if request.method == 'POST':
		form = forms.UpdateForm(request.POST)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect('/projects/' + pid)
	else:
		init = {'project': pid, 'mod_user': request.user.id}
		form = forms.UpdateForm(initial=init)
	context = {'form': form, 'pid': pid}
	return render(request, 'projects/add_update.html', context)


class ProjectListView(PermissionRequiredMixin, ListView):
	raise_exception = True
	permission_required = 'projects.change_project' # not really accurate
	template_name = 'projects/project_list.html' 
	model = models.Project

	def get_queryset(self, **kwargs):
		qs = super(ProjectListView, self).get_queryset(**kwargs)
		#assert isinstance(qs, QuerySet)
		if self.request.GET: # not self.request.method == 'GET' b/c default filter
			if self.request.GET.get('customer'):
				qs = qs.filter(customer=self.request.GET.get('customer'))
			if self.request.GET.get('work_type'):
				qs = qs.filter(work_type=self.request.GET.get('work_type'))
			if self.request.GET.get('status'):
				qs = qs.filter(status=self.request.GET.get('status'))
			if self.request.GET.get('engineer'):
				qs = qs.filter(engineer=self.request.GET.get('engineer'))
				#qs = qs.filter(Q(engineer=self.request.GET.get('engineer')) | 
				#				Q(lead_eng=self.request.GET.get('engineer')))
		else:
			qs = qs.filter(status='INP') # default to only show in-progress
		return qs

	def get_context_data(self, **kwargs):
		context = super(ProjectListView, self).get_context_data(**kwargs)
		if self.request.GET:
			data = {
				'customer': self.request.GET.get('customer'), 
				'work_type': self.request.GET.get('work_type'), 
				'status': self.request.GET.get('status'), 
				'engineer': self.request.GET.get('engineer')}
			context['form'] = forms.ProjectFilter(data)
		else:
			context['form'] = forms.ProjectFilter(initial={'status':'INP'})
		context['work_opts'] = models.Project.WORK_TYPES
		context['status_opts'] = models.Project.STATUS
		return context


@login_required
@permission_required('projects.change_update', raise_exception=True)
def project_updates(request, pid):
	qs = models.Update.objects.filter(project=pid)
	context = {'updates': qs, 'stage_opts': models.Update.STAGES, 'project':models.Project.objects.get(pk=pid)}
	return render(request, 'projects/update_list.html', context)


class CustomerListView(PermissionRequiredMixin, ListView):
	raise_exception = True
	permission_required = 'projects.add_customer'
	template_name = 'projects/customer_list.html' 
	model = models.Customer
	queryset = models.Customer.objects.order_by('name')
	paginate_by = 50	

	def get_context_data(self, **kwargs):
		context = super(CustomerListView, self).get_context_data(**kwargs)
		context['form'] = forms.CustomerForm()
		return context


@require_POST
@permission_required('projects.add_customer', raise_exception=True)
def add_customer(request):
	form = forms.CustomerForm(request.POST)
	if form.is_valid():
		form.save()
	return HttpResponseRedirect('/projects/customers/')


@permission_required('projects.change_checklist', raise_exception=True)
def complete_checklist(request, pid, gate):
	if request.method == 'POST':
		formset = forms.ChecklistFormset(request.POST)
		if formset.is_valid():
			milestone = models.Milestone.objects.filter(project=pid).get(description=models.Defaults.GATE_LIST[int(gate)-1][0])
			for frm in formset:
				cli = frm.save(commit=False)
				cli.checklist = milestone
				# ^ could silently mess up if there are somehow two milestones on a project with the same name
				cli.save()
			milestone.completion_date = date.today()
			milestone.save()
			return HttpResponseRedirect('/projects/'+pid)
	else:
		# where will the defaults be located?
		checklist = models.Defaults.GATE_LIST[int(gate)-1][1]
		init = {
			'form-TOTAL_FORMS':str(len(checklist)), # may need to be dynamic
			'form-INITIAL_FORMS':'0',
			'form-MIN_NUM_FORMS':'',
			'form-MAX_NUM_FORMS':'',
		}
		for i in range(len(checklist)):
			init['form-'+str(i)+'-name'] = checklist[i][0]
			init['form-'+str(i)+'-responsible'] = checklist[i][1]
			init['form-'+str(i)+'-completed'] = False
			init['form-'+str(i)+'-remarks'] = ''
			# don't know if the pre-existing remarks are supposed to be added or not
		formset = forms.ChecklistFormset(init)
	context = {'formset': formset, 
				'gate':{'number':gate, 'name':models.Defaults.GATE_LIST[int(gate)-1][0]}, 
				'pid':pid, 
				'responsible':models.Defaults.RESPONSIBLE, 
				'item_desc': models.Defaults.GATE_LIST[int(gate)-1][2]}
	return render(request, 'projects/checklist.html', context)

@login_required
def download_checklist(request, pid, gate):
	translation.activate('en')
	proj = get_object_or_404(models.Project, pk=pid)
	ms = models.Milestone.objects.filter(project=pid).get(description=str(models.Defaults.GATE_LIST[int(gate)-1][0]))
	if ms.is_complete():
		filename = proj.name + ' - ' + str(models.Defaults.GATE_LIST[int(gate)-1][0]) + ' Gate Checklist.xlsx'
		response = HttpResponse(generate_gate_checklist(ms, gate), content_type='application/vnd.ms-excel')
		response['Content-Disposition'] = 'attachment; filename="' + filename + '"'
		return response
	elif not ms.is_complete():
		pass
		#raise error

projects/templates/projects/add_project.html
{% extends "page.html" %}

{% load static i18n %}

{% block title %} Add Project {% endblock %}

{% block pagecontent %}

<div class="container">
	<div class="border-around">
	<h3>{% trans "Add New Project" %}</h3>
	<form method="POST" action="{% url 'projects:addproject' %}">
		{% csrf_token %}
		{{formset.management_form}}
		<table id="project-info-table" class="table">
			{{proj_form.as_table}}
		</table>
		<div class="table-reponsive">
		<table id="milestone-table" class="table">
			<tr id="milestone-table-header-row">
				<th>{{formset.empty_form.description.label|capfirst}}</th>
				<th>{{formset.empty_form.deadline.label|capfirst}}</th>
			</tr>
			{% for frm in formset %}
			<tr class="form">
				<td>{{frm.description.value}}</td>
				<td style="display: none;">{{frm.description}}</td>
				<td>
					{{frm.deadline}}
					{% if request.method == 'POST' %}
					{{frm.deadline.errors}}
					{% endif %}
				</td>
			</tr>
			{% endfor %}
		</table>
		</div>
		<input type="submit" value="{% trans 'Submit' %}">
	</form>
	{% comment %}
	<!-- this div only used in different add/remove form js -->
	<div >
		<table id="empty-form" style="display: none;">
			<tr class="fake-form">
				<td>{{formset.empty_form.description}}</td>
				<td>{{formset.empty_form.deadline}}</td>
			</tr>
		</table>
	</div>
	{% endcomment %}
	</div>
</div>

{% endblock pagecontent %}

{% comment %}
{% block scripts %}

<script>$(document).ready(addDeleteForms())</script>

{% endblock %}
{% endcomment %}

projects/templates/projects/add_update.html
{% extends "page.html" %}

{% load i18n %}

{% block title %} Add Update {% endblock %}

{% block pagecontent %}

<div class="container">
	<div class="border-around" style="display: inline-block;">
	<h3>{% trans "Add Project Update" %}</h3>
	<form method="POST" action="{% url 'projects:addupdate' pid %}">
		{% csrf_token %}
		<table>
			{{form.as_table}}
		</table>
		<input type="submit" value="{% trans 'Submit' %}">
	</form>
	</div>
</div>

{% endblock %}

projects/templates/projects/customer_list.html
{% extends "page.html" %}

{% load custom i18n %}

{% block title %} Customer List {% endblock %}

{% block pagecontent %}

<div class="pad-list">
	<h3>{% trans "Customer List" %}</h3>
	<div class="table-responsive">
		<table class="table table-striped">
			<tr>  
				<th>{{customer_list.model|verbose_name:'name'|title}}</th>
			</tr>
			<tr>
				<td>
					<form action="{% url 'projects:addcustomer' %}" method="post">
						{% csrf_token %}
						{{form.name}}
						<input type="submit" value="{% trans 'Add' %}">
					</form>
				</td>
			</tr>
			{% for c in customer_list %}
			<tr class="notice-me"> 
				<td> {{c.name}} </td>
			</tr>
			{% endfor %}
		</table>
		{% if not object_list %}
			<p>{% trans "No customers found" %}</p>
		{% endif %}
	</div>
	<div class="row">
		<div class="col-xs-4 col-md-5"><hr style="border:none;color:#333;background-color:#333" /></div>
		<div class="col-xs-4 col-md-2" style="text-align: center;">
			<span style="font-size: 1.5em;">
				{% if page_obj.has_previous %}
					<a href="{% url 'overtime:list' page_obj.previous_page_number %}"><i class="glyphicon glyphicon-chevron-left" style="color: #333"></i></a>
				{% else %}
					<!-- placeholder to ensure it remains centered -->
					<i class="glyphicon glyphicon-chevron-left" style="visibility: hidden;"></i>
				{% endif%}
				<span>{{page_obj.number}}</span>
				{% if page_obj.has_next %}
					<a href="{% url 'overtime:list' page_obj.next_page_number %}"><i class="glyphicon glyphicon-chevron-right" style="color: #333"></i></a>
				{% else %}
					<!-- placeholder to ensure it remains centered -->
					<i class="glyphicon glyphicon-chevron-right" style="visibility: hidden"></i>
				{% endif%}
			</span>
		</div>
		<div class="col-xs-4 col-md-5"><hr style="border:none;color:#333;background-color:#333" /></div>
	</div>
</div>

{% endblock pagecontent %}

projects/templates/projects/project.html
{% extends "page.html" %}

{% load custom i18n %}

{% block title %} {{project.name}} {% endblock %}


{% block pagecontent %} 

<div class="container">
	<div class="row">
		<h1> {{project.name}} </h1>
		<hr/>
		<div class="col-md-6">
			<h3> {{project.customer}} </h3>
			<p>{{project.work_type|human_readable:work_opts}}</p>
			<!-- wow this stuff isn't great -->
			{% if project.eastek_pn %}
				<p><b>{{project|verbose_name:'eastek_pn'|capfirst}}: </b>{{project.eastek_pn}}</p>
			{% else %}
				<form method="POST" action="{% url 'projects:partnumupdate' project.id 'eastek' %}">
				{% csrf_token %}
				<b>{{project|verbose_name:'eastek_pn'|capfirst}}:</b>
				{{epn_form.partnum}}
				<input type="submit" value="{% trans 'Submit' %}">
				</form>
			{% endif %}

			{% if project.cust_pn %}
				<p><b>{{project|verbose_name:'cust_pn'|capfirst}}: </b>{{project.cust_pn}}</p>
			{% else %}
				<form method="POST" action="{% url 'projects:partnumupdate' project.id 'customer' %}">
				{% csrf_token %}
				<b>{{project|verbose_name:'cust_pn'|capfirst}}:</b>
				{{cpn_form.partnum}}
				<input type="submit" value="{% trans 'Submit' %}">
				</form>
			{% endif %}
			<!-- especially bad part ends here -->
			<form method="POST" action="{% url 'projects:statusupdate' project.id %}">
			{% csrf_token %}
			{{projstatus}}
			<input type="Submit" value="{% trans 'Update' %}">
			</form>

			{# <p><b>{% trans "Lead Engineer" %}:</b>{{project.lead_eng}}</p> #}
			{% if request.LANGUAGE_CODE == 'zh-hans' %}
			<p><b>{% trans "Engineers" %}:</b>
				{% for eng in project.engineer.all %}
				{{eng.name}} &nbsp;
				{% endfor %}
			</p>
			{% else %}
			<p><b>{% trans "Engineers" %}:</b>{{project.engineer.all|join:', '}}</p>
			{% endif %}

			{% if request.user.get_employee and not request.user.get_employee in project.engineer.all %}
			<form method="POST" action="{% url 'projects:joinproject' project.id %}">
			{% csrf_token %}
			<input type="submit" value="{% trans 'Join Project' %}">
			</form>
			{% endif %}
		</div>
		<div class="col-md-6">
			<h3> {% trans "Milestones" %} </h3>
			{% if milestones %}
			<table class="table">
				<tr>
					{# it's okay to use the first milestone in the list because this won't execute without one #}
					<th>{{milestones.0|verbose_name:'deadline'|title}}</th>
					<th>{{milestones.0|verbose_name:'description'|title}}</th>
					<th>{% trans "Complete" %}</th>
				</tr>
					{% for ms in milestones %}
					<tr>
						<td>{{ms.deadline}}</td>
						<td>{{ms.description}}</td>
						{% if ms.is_complete %}
						<td>
							{% firstof ms.completion_date 'Yes' %}
							<a href="{% url 'projects:downloadchecklist' project.id forloop.counter %}"><span class="glyphicon glyphicon-save" style="font-size: 1.2em" aria-hidden="true"></span></a>
						</td>
						{% elif perms.projects.change_checklist %}
						{% ifchanged ms.is_complete %}
						<td><a href="{% url 'projects:checklist' project.id forloop.counter %}" class="btn btn-default">{% trans "Gate Checklist" %}</a></td>
						{% else %}
						<td><a href="#" class="btn btn-default disabled">{% trans "Gate Checklist" %}</a></td>
						{% endifchanged %}
						{% else %}
						<td><a href="#" class="btn btn-default disabled">{% trans "Gate Checklist" %}</a></td>
						{% endif %}
					</tr>
					{% endfor %}
			</table>
			{% else %}
			<hr/>
			<p> {% trans "No milestones set" %}</p>
			{% endif %}
		</div>
	</div>
	<div class="row">
		<div class="col-md-12">
		<h3> {% trans "Status" %} </h3>
		{% if status %}
		<table class="table">
			<tr>
				<th>{{status|verbose_name:'mod_date'|title}}</th>
				<th>{{status|verbose_name:'stage'|title}}</th>
				<th>{{status|verbose_name:'action_required'|title}}</th>
				<th>{{status|verbose_name:'estimated_hours'|title}}</th>
			</tr>
			<tr>
				<td>{{status.mod_date}}</td>
				<td>{{status.stage|human_readable:stage_opts}}</td>
				<td>{{status.action_required}}</td>
				<td>{{status.estimated_hours}}</td>
			</tr>
		</table>
		{% else %}
		<hr/>
		<p>{% trans "No updates recorded" %}</p>
		{% endif %}
		<a href="{% url 'projects:addupdate' project.id %}" class="btn btn-default">{% trans "Update Status" %}</a>
		<a href="{% url 'projects:updates' project.id %}" class="btn btn-default">{% trans "View Previous" %}</a>
		</div>
	</div>
</div>


{% endblock pagecontent %}

projects/templates/projects/project_list.html
{% extends "page.html" %}

{% load custom i18n %}

{% block title %} Project List {% endblock %}

{% block pagecontent %} 

<div class="pad-list">
	<h3>{% trans "Project List" %}</h3>
	<form action="{% url 'projects:projectlist' %}" method="get">
		{{form}}
		<input type="submit" value="{% trans 'Filter' %}">
	</form>
	<div class="table-responsive">
		<table class="table table-striped">
			<tr>  
				<th>{{object_list.model|verbose_name:'name'|title}}</th>
				<th>{{object_list.model|verbose_name:'customer'|title}}</th>
				<th>{{object_list.model|verbose_name:'work_type'|title}}</th>
				<th>{{object_list.model|verbose_name:'status'|title}}</th>
				<th>{{object_list.model|verbose_name:'engineer'|capfirst}}</th>
			</tr>
			{% for p in object_list %}
			<tr class="notice-me" onclick="document.location = '{% url 'projects:dashboard' p.id %}'"> 
				<td> {{p.name}} </td>
				<td> {{p.customer}} </td>
				<td> {{p.work_type|human_readable:work_opts}} </td>
				<td> {{p.status|human_readable:status_opts}} </td>
				{% if request.LANGUAGE_CODE == 'zh-hans' %}
				<td>
					{% for eng in p.engineer.all %}
					{{eng.name}} &nbsp;
					{% endfor %}
				</td>
				{% else %}
				<td> {{p.engineer.all|join:', '}} </td>
				{% endif %}
			</tr>
			{% endfor %}
		</table>
		{% if not object_list %}
			<p>{% trans "No projects found" %}</p>
		{% endif %}
	</div>
</div>

{% endblock pagecontent %}