employees/urls.py
from django.conf.urls import url
from . import views

# Need to learn Regex for making the URLs
#   and how the URLs/requests allow certain records to be displayed
app_name = 'employees'
urlpatterns = [
	url(r'^$', views.list, name='list'),
	url(r'^(?P<emp_id>add|[0-9]{4,5})/$', views.individual, name='detail'),
	#url(r'^(?P<emp_id>add)/$', views.individual, name='detail'),
	url(r'^(?P<emp_id>[0-9]{4,5})/create_account/$', views.generate_account, name='genaccount'),
]

users/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'users'
urlpatterns = [
	#url(r'^settings/$', auth_views.PasswordChangeView.as_view(template_name='users/pwd_change.html', success_url='/'), name='settings'),
	url(r'^set-password/$', views.change_password, name='setpassword'),
	#url(r'^set-homepage/$', views.set_home_projects, name='setlinks'),
]

employees/models.py
import re

from django.db import models
from django.conf import settings
from django.core.exceptions import ValidationError
from django.contrib.auth import get_user_model
from django.contrib.auth.models import Group
from django.utils.translation import ugettext_lazy as _


class Employee(models.Model):
	"""contains the data from EmployeeInfo table"""
	class Meta:
		ordering = ['emp_id']
		verbose_name = _('Employee')


	EASTEK_EMAIL_REGEX = r'^[a-z]+\.[a-z]+@(?:eastek)(?:-intl|international)\.com$'
	ASSISTANT_ENG = 'AEN'
	ENGINEER = 'ENG'
	SENIOR_ENG = 'SEN'
	LEADER = 'LDR'
	CLERK = 'CLK'
	TOOLING_ENG = 'TEN'
	POSITIONS = (
		(ASSISTANT_ENG, _('Assistant Engineer')),
		(ENGINEER, _('Engineer')),
		(SENIOR_ENG, _('Senior Engineer')),
		(LEADER, _('Engineer Leader')),
		(CLERK, _('Clerk')),
		(TOOLING_ENG, _('Tooling Engineer')),
	)
	MECHANICAL = 'MECH'
	ELECTRONIC = 'ELEC'
	SUPPORT = 'SUPP'
	TOOLING = 'TOOL'
	TEAMS = (
		(MECHANICAL, _('Mechanical')),
		(ELECTRONIC, _('Electronics')),
		(SUPPORT, _('Support')),
		(TOOLING, _('Tooling')),
	)

	# Need this to be CharField b/c emp_ids start w/ 0
	emp_id = models.CharField(max_length = 5, primary_key=True, verbose_name=_('employee ID'))
	name = models.CharField(max_length=25, verbose_name=_('name'))
	english_name = models.CharField(max_length=40, verbose_name=_('english name'))
	position = models.CharField(max_length=3, choices=POSITIONS, verbose_name=_('position')) # will need translating fix 
	is_active = models.BooleanField(default=True, verbose_name=_('employed'))
	is_leader = models.BooleanField(default=False, verbose_name=_('is leader')) # need this because support leader isn't LDR
	team = models.CharField(max_length=4, choices=TEAMS, verbose_name=_('team'))
	leader = models.ForeignKey('self', on_delete=models.PROTECT, limit_choices_to={'is_leader': True}, verbose_name=_('leader'))
	email = models.EmailField(unique=True, verbose_name=_('email'))
	join_date = models.DateField(verbose_name=_('join date'))
	ret_date = models.DateField(blank=True, null=True, verbose_name=_('retire date'))
	account = models.OneToOneField(settings.AUTH_USER_MODEL, null=True,
		on_delete=models.SET_NULL, blank=True, verbose_name=_('user account')) 

	def __str__(self):
		return self.english_name

	def get_absolute_url(self):
		from django.urls import reverse
		return reverse('employees.detail', args=[self.emp_id])

	def get_leaders(): # don't think this is used
		leaders = []
		for ldr in Employee.objects.filter(is_leader=True):
			leaders.append((ldr.emp_id, ldr.english_name))
		return leaders

	def validate_email(email): 
		#regex for eastek email & no duplicates
		email.lower()
		if re.match(Employee.EASTEK_EMAIL_REGEX, email) == None: # is None ?
			raise ValidationError(_('Email must be a valid @eastek-intl.com or @eastekinternational.com email address'))

	def validate_leader(leader):
		#ensure leader has is_leader field active, shouldn't be triggered b/c ModelChoiceField
		if not leader.is_leader:
			raise ValidationError(_("Employee selected for leader must have 'Is leader' attribute"))

	def validate_emp_id(emp_id):
		if re.match(r'^[0-9]{4,5}$', emp_id) == None:
			raise ValidationError(_('Employee ID must be numerals only and 4-5 digits long'))
	
	def generate_user(self, supress=True):
		# check if custom user is implemented (quit if not?)
		if not self.has_user(): 
			username = self.email.split('@')[0]
			password = self.email.split('.')[0].lower() + '.' + self.emp_id
			User = get_user_model()
			if not User.objects.filter(username=username).exists():
				user = User.objects.create_user(username=username, email=self.email, password=password)
				assert isinstance(user, User), user
				user.groups.add(Group.objects.get(name='default'))
				if self.team == 'SUPP':
					user.groups.add(Group.objects.get(name='support'))
				if self.position == 'ENG' or self.position == 'SEN' or self.position == 'TEN' or self.position == 'LDR':
					user.groups.add(Group.objects.get(name='engineer'))
				if not self.is_active:
					user.is_active = False
					user.save()
				self.account = user
				self.save()
				return user
			elif not supress:
				return False # user already exists
		elif not supress:
			return False # employee has account

	# returns the status of the presence of an associated user account
	def has_user(self):
		User = get_user_model()
		return isinstance(self.account, User)

	# if this user has been marked as retired, archive the associated account
	def archive_account(self):
		if not self.is_active and self.has_user():
			self.account.is_active = False
			self.account.save()

employees/forms.py
from django import forms
from django.core.exceptions import ValidationError
#from django.core.validators import validate_email
from django.utils.translation import ugettext_lazy as _

from .models import Employee


class FilterListForm(forms.Form):
	"""handles sorting in the list view"""
	position = forms.ChoiceField(required=False, choices=(('',''),) + Employee.POSITIONS, label=_('Position')) # label needs work
	team = forms.ChoiceField(required=False, choices=(('',''),) + Employee.TEAMS, label=_('Team'))
	leader = forms.ModelChoiceField(required=False, queryset=Employee.objects.filter(is_leader=True), empty_label='',label=_('Leader')) # ModelChoiceField? - NO (okay now I wish i knew why)
	ret = forms.BooleanField(required=False, label=_('Retired'))

class IndividualForm(forms.ModelForm):
	"""handles displaying detail view info"""
	leader = forms.ModelChoiceField(queryset=Employee.objects.filter(is_leader=True), validators=[Employee.validate_leader], empty_label='', label=_('Leader'))
	# true if a user account is to be created for the employee (unbound), or there is already an account (bound)user_acc = forms.BooleanField(required=False, label='User account')
	email = forms.EmailField(validators=[Employee.validate_email], label=_('Email')) # make sure other validators remain
	emp_id = forms.CharField(min_length=4, max_length=5, validators=[Employee.validate_emp_id], label=_('Employee ID'))

	class Meta:
		model = Employee
		fields = ['emp_id', 'name', 'english_name', 'position', 'is_active', 'is_leader', 
			'team', 'leader', 'email', 'join_date', 'ret_date']
	
	def clean(self):
		super(IndividualForm, self).clean()
		if not self.cleaned_data['is_active'] and self.cleaned_data['ret_date'] == None:
			self.add_error(self.ret_date, ValidationError(_('Retired employees must have a retire date'))) # add to retire date
		if self.cleaned_data['ret_date'] != None and self.cleaned_data['is_active']:
			self.add_error(self.is_active, ValidationError(_('Employees with a retire date must be marked as retired'))) # add to is_active
		if self.cleaned_data['is_leader'] and self.cleaned_data['leader'].emp_id != self.cleaned_data['emp_id']:
			self.add_error('leader', ValidationError(_('A team leader must be their own team leader')))

	def clean_email(self):
		return self.cleaned_data['email'].lower()

employees/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404
from django.views.generic import ListView, DetailView
from django.contrib.auth.decorators import login_required, permission_required
from django.views.decorators.http import require_POST
from django.http import HttpResponseRedirect, HttpResponseNotFound

from .models import Employee
from .forms import FilterListForm, IndividualForm


@login_required
@permission_required(['employees.add_employee', 'employees.change_employee'], raise_exception=True)
def list(request):
	# Returns list of all employees (filtered by ___)
	emps = Employee.objects.all()
	form = FilterListForm()
	if request.GET: # true only when there are values for the GET attribute (request.method == 'GET')
		filters = {'team':request.GET.get('team'),
				'leader':request.GET.get('leader'),
				'position':request.GET.get('position'),
				'retired':request.GET.get('ret')=='on'}
		if filters['team'] != '':
			emps = emps.filter(team=filters['team'])
		if filters['leader'] != '':
			emps = emps.filter(leader=filters['leader'])
		if filters['position'] != '':
			emps = emps.filter(position=filters['position'])
		form = FilterListForm(filters)
	emps = emps.filter(is_active=not request.GET.get('ret')=='on')
	context = {
		'emps': emps,
		'filterform': form
	}
	return render(request, 'employees/list.html', context)


@login_required
@permission_required(['employees.add_employee', 'employees.change_employee'], raise_exception=True)
def individual(request, emp_id):
	# Returns detail view of one employee (as a form)
	# GET requests supress errors, POST requests display
	context = {}
	if request.method == 'POST':
		# validate & save data (new or edit employee)
		if Employee.objects.filter(pk=request.POST.get('emp_id')).count() == 1:
			emp = Employee.objects.get(pk=request.POST.get('emp_id'))
			form = IndividualForm(request.POST, instance=emp, initial={'user_acc': emp.has_user()}) # is this actually what is wanted? does request have presidence? what about overriding the user account field?
		else:
			form = IndividualForm(request.POST)
		if form.is_valid():
			# check against other validation methods? (email domain, etc.)
			emp = form.save()
			context['saved'] = True
			if not form.cleaned_data['is_active'] and emp.has_user():
				emp.archive_account() # might not want this (good security procedure though)
		else:
			pass
		# common context	
		context['arg'] = request.POST.get('emp_id')
	else:
		if emp_id == 'add':
		# create new blank form
			form = IndividualForm()
			context['arg'] ='add'
		else:
			emp = get_object_or_404(Employee, pk=emp_id)
			assert emp.emp_id == emp_id
			form = IndividualForm(instance=emp, initial={'user_acc': emp.has_user()})
			context['emp'] = emp
			context['arg'] = emp.emp_id
	context['indvform'] = form
	return render(request, 'employees/detail.html', context)

@require_POST
@permission_required(['users.add_user', 'employees.change_employee'], raise_exception=True)
def generate_account(request, emp_id):
	emp = get_object_or_404(Employee, pk=emp_id)
	if emp.generate_user():
		return HttpResponseRedirect('/employees/')
	else:
		return HttpResponseNotFound()

employees/templates/employees/detail.html
{% extends "page.html" %}

{% load i18n %}

{% block title %} {% firstof emp.english_name 'Add Employee' %} {% endblock title %}

{% block pagecontent %}
<div class="container">
	<div class="border-around" style="display: inline-block;">
	{% if arg != 'add' %}
	<h3>{% firstof emp.name indvform.name.value %} {% trans "Employee Record" %}</h3>
	{% else %}
	<h3>{% trans "Add Employee Record" %}</h3>
	{% endif %}
	{% if saved %}
		<span> {% trans "Employee information saved successfully" %}</span>
	{% endif %}
	<!-- main display/form -->
	<form action="{% url 'employees:detail' arg %}" method="post">
		{% csrf_token %}
		<table>
			{{indvform.as_table}}
		</table>
		<input type="submit" value="{% trans 'Save' %}">
	</form>
	</div>
{% endblock pagecontent %}

employees/templates/employees/list.html
{% extends "page.html" %}

{% load custom i18n %}

{% block title %} Employee List {% endblock %}

{% block pagecontent %}
<div class="pad-list">
	<h3>{% trans "Employee List" %}</h3>
	<div class="container-fluid">
		<div class="row">
			<!-- filter form -->
			<div class="col-md-11">
				<form action="{% url 'employees:list' %}" method="get">
					{{ filterform }}
					<input type="Submit" value="{% trans 'Filter' %}">
				</form>
			</div> 
			<div class="col-md-1">
				<!-- new user button -->
				<a href="{% url 'employees:detail' 'add' %}" class="btn btn-default"> {% trans "Add Employee" %} </a>
			</div>
		</div>
	</div>
	<!-- employee display table -->
	<div class="table-responsive">
		<table class="table table-striped">
			<tr>  
				<th>{{emps.model|verbose_name:'emp_id'|capfirst}}</th>
				<th>{{emps.model|verbose_name:'name'|title}}</th>
				<th>{{emps.model|verbose_name:'english_name'|title}}</th>
				<th>{{emps.model|verbose_name:'position'|title}}</th>
				<th>{{emps.model|verbose_name:'team'|title}}</th>
				<th>{{emps.model|verbose_name:'leader'|title}}</th>
				<th>{{emps.model|verbose_name:'email'|title}}</th>
				<th>{{emps.model|verbose_name:'account'|title}}</th>
			</tr>
			{% for e in emps %}
				<tr class="notice-me" onclick="document.location = '{% url 'employees:detail' e.emp_id %}'"> 
					<td> {{e.emp_id}} </td>
					<td> {{e.name}} </td>
					<td> {{e.english_name}} </td>
					<td> {{e.get_position_display}} </td>
					<td> {{e.get_team_display}} </td>
					{% if request.LANGUAGE_CODE == 'zh-hans' %}
					<td> {{e.leader.name}} </td>
					{% else %}
					<td> {{e.leader.english_name}} </td>
					{% endif %}
					<td> {{e.email}} </td>
					{% if e.account %}
					<td> {{e.account.username}} </td>
					{% else %}
					<td><form action="{% url 'employees:genaccount' e.emp_id %}" method="post">
						{% csrf_token %}
						<input type="Submit" value="{% trans 'Create Account' %}">
					</form></td>
					{% endif %}
				</tr>
			{% endfor %}
		</table>
		{% if not emps %}
			<p>{% trans "No employee information found" %}</p>
		{% endif %}
	</div>
</div>
{% endblock pagecontent %}