EngSite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.views.generic.base import TemplateView

from users import views as user_views

#from .views import HomeView

urlpatterns = [
    url(r'^$', login_required(TemplateView.as_view(template_name='home.html')), name='landing'),
    url(r'^login/$', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    url(r'^WIP/$', login_required(TemplateView.as_view(template_name='WIP.html')), name='WIP'),
    url(r'^overtime/', include('overtime.urls')),
    url(r'^user/', include('users.urls')),
    url(r'^employees/', include('employees.urls')),
    url(r'^projects/', include('projects.urls')),
    url(r'^admin/', admin.site.urls)
]

employees/urls.py
from django.conf.urls import url
from . import views

# Need to learn Regex for making the URLs
#   and how the URLs/requests allow certain records to be displayed
app_name = 'employees'
urlpatterns = [
	url(r'^$', views.list, name='list'),
	url(r'^(?P<emp_id>add|[0-9]{4,5})/$', views.individual, name='detail'),
	#url(r'^(?P<emp_id>add)/$', views.individual, name='detail'),
	url(r'^(?P<emp_id>[0-9]{4,5})/create_account/$', views.generate_account, name='genaccount'),
]

overtime/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from . import views

app_name = 'overtime'
urlpatterns = [
	url(r'^add/$', views.add_overtime, name='add'),
	url(r'^request/$', views.overtimerequest, name='requestform'),
	#url(r'^list/(?P<page>[0-9]+)/$', login_required(views.OvertimeListView.as_view()), name='list'),
	url(r'^list/(?P<page>[0-9]+)/$', views.overtime_list, name='list'),
	url(r'^list/(?P<page>[0-9]+)/add-actual-hours/$', views.add_actual_hours, name='actualhours'), 
]

projects/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
#from django.views.generic import DetailView
from . import views

app_name = 'projects'
urlpatterns = [
	url(r'^$', login_required(views.ProjectListView.as_view()), name='projectlist'),
	url(r'^(?P<pid>[0-9]+)/$', views.project_page, name='dashboard'),
	url(r'^(?P<pid>[0-9]+)/status_update/$', views.change_project_status, name='statusupdate'),
	url(r'^(?P<pid>[0-9]+)/add_part_number/(?P<org>eastek|customer)/$', views.add_part_number, name='partnumupdate'),
	url(r'^(?P<pid>[0-9]+)/join_project/$', views.add_self_to_project, name='joinproject'),
	url(r'^add/$', views.add_project, name='addproject'),
	#url(r'^(?P<pid>[0-9]+)/milestones/$', views.project_milestones, name='milestones'),
	#url(r'^(?P<pid>[0-9]+)/milestones/completion_status$', views.change_milestone_completion, name='milestonecompletion'),
	url(r'^(?P<pid>[0-9]+)/updates/$', views.project_updates, name='updates'),
	url(r'^(?P<pid>[0-9]+)/updates/add/$', views.add_update, name='addupdate'),
	url(r'^(?P<pid>[0-9]+)/gate/(?P<gate>[12345])/$', views.complete_checklist, name='checklist'),
	url(r'^(?P<pid>[0-9]+)/download/(?P<gate>[12345])/$', views.download_checklist, name='downloadchecklist'),
	url(r'^customers/$', views.CustomerListView.as_view(), name='customers'),
	url(r'^customers/add_new_customer/$', views.add_customer, name='addcustomer'),

]

users/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'users'
urlpatterns = [
	#url(r'^settings/$', auth_views.PasswordChangeView.as_view(template_name='users/pwd_change.html', success_url='/'), name='settings'),
	url(r'^set-password/$', views.change_password, name='setpassword'),
	#url(r'^set-homepage/$', views.set_home_projects, name='setlinks'),
]

employees/models.py
import re

from django.db import models
from django.conf import settings
from django.core.exceptions import ValidationError
from django.contrib.auth import get_user_model
from django.contrib.auth.models import Group
from django.utils.translation import ugettext_lazy as _


class Employee(models.Model):
	"""contains the data from EmployeeInfo table"""
	class Meta:
		ordering = ['emp_id']
		verbose_name = _('Employee')


	EASTEK_EMAIL_REGEX = r'^[a-z]+\.[a-z]+@(?:eastek)(?:-intl|international)\.com$'
	ASSISTANT_ENG = 'AEN'
	ENGINEER = 'ENG'
	SENIOR_ENG = 'SEN'
	LEADER = 'LDR'
	CLERK = 'CLK'
	TOOLING_ENG = 'TEN'
	POSITIONS = (
		(ASSISTANT_ENG, _('Assistant Engineer')),
		(ENGINEER, _('Engineer')),
		(SENIOR_ENG, _('Senior Engineer')),
		(LEADER, _('Engineer Leader')),
		(CLERK, _('Clerk')),
		(TOOLING_ENG, _('Tooling Engineer')),
	)
	MECHANICAL = 'MECH'
	ELECTRONIC = 'ELEC'
	SUPPORT = 'SUPP'
	TOOLING = 'TOOL'
	TEAMS = (
		(MECHANICAL, _('Mechanical')),
		(ELECTRONIC, _('Electronics')),
		(SUPPORT, _('Support')),
		(TOOLING, _('Tooling')),
	)

	# Need this to be CharField b/c emp_ids start w/ 0
	emp_id = models.CharField(max_length = 5, primary_key=True, verbose_name=_('employee ID'))
	name = models.CharField(max_length=25, verbose_name=_('name'))
	english_name = models.CharField(max_length=40, verbose_name=_('english name'))
	position = models.CharField(max_length=3, choices=POSITIONS, verbose_name=_('position')) # will need translating fix 
	is_active = models.BooleanField(default=True, verbose_name=_('employed'))
	is_leader = models.BooleanField(default=False, verbose_name=_('is leader')) # need this because support leader isn't LDR
	team = models.CharField(max_length=4, choices=TEAMS, verbose_name=_('team'))
	leader = models.ForeignKey('self', on_delete=models.PROTECT, limit_choices_to={'is_leader': True}, verbose_name=_('leader'))
	email = models.EmailField(unique=True, verbose_name=_('email'))
	join_date = models.DateField(verbose_name=_('join date'))
	ret_date = models.DateField(blank=True, null=True, verbose_name=_('retire date'))
	account = models.OneToOneField(settings.AUTH_USER_MODEL, null=True,
		on_delete=models.SET_NULL, blank=True, verbose_name=_('user account')) 

	def __str__(self):
		return self.english_name

	def get_absolute_url(self):
		from django.urls import reverse
		return reverse('employees.detail', args=[self.emp_id])

	def get_leaders(): # don't think this is used
		leaders = []
		for ldr in Employee.objects.filter(is_leader=True):
			leaders.append((ldr.emp_id, ldr.english_name))
		return leaders

	def validate_email(email): 
		#regex for eastek email & no duplicates
		email.lower()
		if re.match(Employee.EASTEK_EMAIL_REGEX, email) == None: # is None ?
			raise ValidationError(_('Email must be a valid @eastek-intl.com or @eastekinternational.com email address'))

	def validate_leader(leader):
		#ensure leader has is_leader field active, shouldn't be triggered b/c ModelChoiceField
		if not leader.is_leader:
			raise ValidationError(_("Employee selected for leader must have 'Is leader' attribute"))

	def validate_emp_id(emp_id):
		if re.match(r'^[0-9]{4,5}$', emp_id) == None:
			raise ValidationError(_('Employee ID must be numerals only and 4-5 digits long'))
	
	def generate_user(self, supress=True):
		# check if custom user is implemented (quit if not?)
		if not self.has_user(): 
			username = self.email.split('@')[0]
			password = self.email.split('.')[0].lower() + '.' + self.emp_id
			User = get_user_model()
			if not User.objects.filter(username=username).exists():
				user = User.objects.create_user(username=username, email=self.email, password=password)
				assert isinstance(user, User), user
				user.groups.add(Group.objects.get(name='default'))
				if self.team == 'SUPP':
					user.groups.add(Group.objects.get(name='support'))
				if self.position == 'ENG' or self.position == 'SEN' or self.position == 'TEN' or self.position == 'LDR':
					user.groups.add(Group.objects.get(name='engineer'))
				if not self.is_active:
					user.is_active = False
					user.save()
				self.account = user
				self.save()
				return user
			elif not supress:
				return False # user already exists
		elif not supress:
			return False # employee has account

	# returns the status of the presence of an associated user account
	def has_user(self):
		User = get_user_model()
		return isinstance(self.account, User)

	# if this user has been marked as retired, archive the associated account
	def archive_account(self):
		if not self.is_active and self.has_user():
			self.account.is_active = False
			self.account.save()

EngSite/templates/WIP.html
{% extends "simple.html" %}

{% block title %} Under Contruction {% endblock %}

{% block content %}
<h1>Work In Progress</h1>
<p>This feature is currently under construction</p>
{% endblock content %}

EngSite/templates/base.html
<!DOCTYPE html>
<html class="no-js" lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title> {% block title %} Project Engineering {% endblock %} </title>
    <meta name="description" content="Eastek International Project Engineering">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    {% load static %}
    <!-- need own icon/favicon -->
    <link rel="icon" href="{% static 'img/eastek_icon.png' %}"/>
    <link rel="apple-touch-icon" href="{% static 'img/eastek_icon.png' %}"/>
    <!-- Place favicon.ico in the root directory -->

    <link rel="stylesheet" href="{% static 'css/normalize.css' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous"/>
    <link rel="stylesheet" href="{% static 'css/main.css' %}"/>

    <script src="{% static 'js/vendor/modernizr-2.8.3.min.js' %}"></script>
</head>
<body>
    <!--[if lt IE 8]>
        <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->

    <!-- Main content goes here, page view will provide more hooks -->
    {% block content %} {% endblock %}

    <!-- jQuery and bootstrap javascript -->
    <script src="https://code.jquery.com/jquery-1.12.0.min.js"></script>
    <script>window.jQuery || document.write('<script src="{% static "js/vendor/jquery-1.12.0.min.js" %}"><\/script>')</script>
    <script src="{% static 'js/plugins.js' %}"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script> $.fn.modal || document.write('<script src="{% static "js/vendor/bootstrap.min.js" %}"><\/script>')</script>
    <script src="{% static 'js/main.js' %}"></script>
    {% block pagescripts %} {% endblock %}
</body>
</html>

EngSite/templates/home.html
{% extends "page.html" %}

{% load static i18n %}

{% block pagecontent %}
<script src="https://use.fontawesome.com/bc6f602dde.js"></script>
<div class="container-fluid">
	<div class="row">
		<div class="col-md-8 col-md-offset-2 col-xs-12">
		<div class="row">
			<div class="col-lg-4 col-md-6 col-xs-12" style="text-align: center; padding: 2%">
				{% if request.user.get_employee %}
				<a href="{% url 'overtime:add' %}">
					<i class="fa fa-user-plus" aria-hidden='true' style="font-size: 15em;"></i>
					<h3 class="no-show-text-link">{% trans "Request Overtime" %}</h3>
				</a>
				{% elif perms.overtime.view_overtime %}
				<a href="{% url 'overtime:list' 1 %}">
					<i class="fa fa-address-card-o" aria-hidden='true' style="font-size: 15em;"></i>
					<h3 class="no-show-text-link">{% trans "Overtime Records" %}</h3>
				</a>
				{% endif %}
			</div>
			<div class="col-lg-4 col-md-6 col-xs-12" style="text-align: center; padding: 2%">
				<a href="{% url 'projects:projectlist' %}?customer=&work_type=&status=INP&engineer={{request.user.employee.emp_id}}">
					<i class="fa fa-list-alt" aria-hidden='true' style="font-size: 15em;"></i>
					<h3 class="no-show-text-link">{% trans "My Projects" %}</h3>
				</a>
			</div>
			<div class="col-lg-4 col-md-6 col-xs-12" style="text-align: center; padding: 2%">
				{% if perms.projects.add_project %}
				<a href="{% url 'projects:addproject' %}">
					<span class="fa-stack" style="font-size: 7.5em;">
						<i class="fa fa-plus fa-stack-1x" aria-hidden='true' style="top: 10px"></i>
						<i class="fa fa-folder-o fa-stack-2x" aria-hidden='true'></i>
					</span>
					<h3 class="no-show-text-link">{% trans "Add New Project" %}</h3>
				</a>
				{% endif %}
			</div>
			<div class="col-lg-4 col-md-6 col-xs-12" style="text-align: center; padding: 2%">
				{% if request.user.projlink1 %}
				<a href="{% url 'projects:dashboard' request.user.projlink1.id %}">
					<i class="fa fa-file-text-o" aria-hidden='true' style="font-size: 15em;"></i>
					<h3 class="no-show-text-link">{{request.user.link1txt}}</h3>
				</a>
				{% endif %}
			</div>
			<div class="col-lg-4 col-md-6 col-xs-12" style="text-align: center; padding: 2%">
				{% if request.user.projlink2 %}
				<a href="{% url 'projects:dashboard' request.user.projlink2.id %}">
					<i class="fa fa-file-text-o" aria-hidden='true' style="font-size: 15em;"></i>
					<h3 class="no-show-text-link">{{request.user.link2txt}}</h3>
				</a>
				{% endif %}
			</div>
			<div class="col-lg-4 col-md-6 col-xs-12" style="text-align: center; padding: 2%">
				{% if request.user.projlink3 %}
				<a href="{% url 'projects:dashboard' request.user.projlink3.id %}">
					<i class="fa fa-file-text-o" aria-hidden='true' style="font-size: 15em;"></i>
					<h3 class="no-show-text-link">{{request.user.link3txt}}</h3>
				</a>
				{% endif %}
			</div>
		</div>
		</div>
	</div>
</div>

{% endblock pagecontent %}

{% block scripts %}
{% endblock %}

EngSite/templates/page.html
{% extends "base.html" %}

{% load static i18n %}

{% block content %}
{% block navbar %}
{# defaut navbar (probably won't override this) #}
<nav class="navbar navbar-default navbar-fixed-top">
	<div class="container-fluid">
	<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<div class="navbar-brand" style="text-align: center; padding: 0;"><a href="{% url 'landing' %}"><img src="{% static 'img/eastek_logo_header.png' %}" style="vertical-align: middle;"></a></div>
		</div>

	<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse" id="navbar-collapse">
			<ul class="nav navbar-nav">
			<!-- ========== Overtime Button Logic ========== -->
				{% if perms.overtime.view_overtime %}
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> {% trans "Overtime" %} <span class="caret"></span></a>
					<ul class="dropdown-menu">
						{% if request.user.get_employee %}
						<li><a href="{% url 'overtime:add' %}">{% trans "Request Overtime" %}</a></li>
						{% endif %}
						<li><a href="{% url 'overtime:requestform' %}">{% trans "Download Form" %}</a></li>
						<li><a href="{% url 'overtime:list' 1 %}">{% trans "View All" %}</a></li>
					</ul>
				</li>
				{% elif request.user.get_employee %}
				<li><a href="{% url 'overtime:add' %}">{% trans "Overtime" %}</a></li>
				{% endif %}
			<!-- ========== Project Dropdown ========== -->
				{% if perms.projects.add_update %}
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> {% trans "Projects" %} <span class="caret"></span></a>
					<ul class="dropdown-menu">
						<li><a href="{% url 'projects:projectlist' %}?customer=&work_type=&status=INP&engineer={{request.user.employee.emp_id}}">{% trans "My Projects" %}</a></li>
						{% if perms.projects.add_project %}
						<li><a href="{% url 'projects:addproject' %}">{% trans "Add New Project" %}</a></li>
						{% endif %}
						<li role="separator" class="divider"></li>
						<li><a href="{% url 'projects:projectlist' %}">{% trans "All Projects" %}</a></li>
						<li><a href="{% url 'projects:customers' %}">{% trans "Customer List" %}</a></li>
					</ul>
				</li>
				{% endif %}
			<!-- ========== Employee Info Button Logic ========== -->
				{% if perms.employees.add_employee and perms.employees.change_employee %}
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> {% trans "Employees" %} <span class="caret"></span></a>
					<ul class="dropdown-menu">
						<li><a href="{% url 'employees:list' %}">{% trans "View All" %}</a></li>
						<li><a href="{% url 'employees:detail' 'add' %}">{% trans "Add New Employee" %}</a></li>
					</ul>
				</li>
				{% endif %}
			<!-- ========== Account Drop Down ========== -->
			</ul>
			<ul class="nav navbar-nav navbar-right">
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> {% trans "Account" %} <span class="caret"></span></a>
					<ul class="dropdown-menu">
						<li class="dropdown-header">{% trans "Settings" %}</a></li>
						{% if request.user.is_staff %}
						<li><a href="{% url 'admin:index' %}">{% trans "Admin Site" %}</a></li>
						{% endif %}
						<li><a href="{% url 'users:setpassword' %}">{% trans "Change Password" %}</a></li>
						{#<li><a href="{% url 'users:setlinks' %}">{% trans "Set Homepage Links" %}</a></li>#}
						<li class="dropdown-header">{% trans "Language" %}</a></li>
						<li><div class="btn-group" role="group" style="padding-left: 3px">
							<button id="set-lang-en" type="button" class="btn btn-default">{% trans "English" %}</button>
							<button id="set-lang-zh" type="button" class="btn btn-default">{% trans "Chinese" %}</button>
						</div></li>
						<li role="separator" class="divider"></li>
						<li><a href="{% url 'logout' %}">{% trans "Logout" %}</a></li>
					</ul>
				</li>
			</ul>
		</div><!-- /.navbar-collapse -->
	</div><!-- /.container-fluid -->
</nav>
{% endblock navbar %}

<div class="nav-pad">
{% block pagecontent %}
	<p> {% trans "There was a problem loading the page content"} </p>
{% endblock pagecontent%}
</div>

{% endblock content %}

{% block pagescripts %}
<script>$(document).ready(changeLang())</script>
{% block scripts %} {% endblock %}
{% endblock %}

EngSite/templates/simple.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %} Project Engineering {% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <style>

        * {
            line-height: 1.2;
            margin: 0;
        }

        html {
            color: #888;
            display: table;
            font-family: sans-serif;
            height: 100%;
            text-align: center;
            width: 100%;
        }

        body {
            display: table-cell;
            vertical-align: middle;
            margin: 2em auto;
        }

        h1 {
            color: #555;
            font-size: 2em;
            font-weight: 400;
        }

        p {
            margin: 0 auto;
            width: 280px;
        }

        @media only screen and (max-width: 280px) {

            body, p {
                width: 95%;
            }

            h1 {
                font-size: 1.5em;
                margin: 0 0 0.3em;
            }

        }

    </style>
</head>
<body>
    {% block content %} {% endblock %}
</body>
</html>
<!-- IE needs 512+ bytes: http://blogs.msdn.com/b/ieinternals/archive/2010/08/19/http-error-pages-in-internet-explorer.aspx -->